services:
  app:
    image: blair-jeon/user-order-api:latest
    ports:
      - 8080:8080
    env_file:
      - .env
    
    depends_on:
      - redis
  
  redis:
    image: redis:8.8
    volumes:
      - redis-data:/data

volumes:
  redis-data: