spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/springdb}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root1234}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:local-dev-secret-key-must-be-long-enough-1234567890}