### Variables
@host = http://localhost:8080
@contentType = application/json

### USER CREATE
POST {{host}}/users
Content-Type: {{contentType}}

{
  "loginId": "jin123",
  "password": "password123!",
  "name": "jin",
  "birthDate": "1998-02-01",
  "email": "jin@test.com"
}

### USER LOGIN
POST {{host}}/users/login
Content-Type: {{contentType}}

{
  "loginId": "jin123",
  "password": "password123!"
}

> {%
    client.global.set("accessToken", response.body.token);
%}

### GET MY INFO
GET {{host}}/users/me
Authorization: Bearer {{accessToken}}

### GET MY PROFILE
GET {{host}}/users/me/profile
Authorization: Bearer {{accessToken}}

### UPDATE MY PROFILE
PATCH {{host}}/users/me/profile
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "name": "jin-update",
  "email": "update@test.com"
}

### CREATE PRODUCT
POST {{host}}/products
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "name": "keyboard",
  "stockQuantity": 100,
  "unitPrice": 150000
}

### SEARCH PRODUCTS
GET {{host}}/products?page=0&size=10&name=key&minPrice=1000&maxPrice=200000
Authorization: Bearer {{accessToken}}

### GET PRODUCT
GET {{host}}/products/1
Authorization: Bearer {{accessToken}}

### UPDATE PRODUCT
PATCH {{host}}/products/1
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "name": "keyboard-update",
  "stockQuantity": 80,
  "unitPrice": 130000
}

### ADD CART ITEM
POST {{host}}/cart/items
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "productId": 1,
  "orderQuantity": 2
}

### GET CART ITEMS
GET {{host}}/cart/items?page=0&size=10
Authorization: Bearer {{accessToken}}

### GET CART ITEM
GET {{host}}/cart/items/1
Authorization: Bearer {{accessToken}}

### UPDATE CART ITEM
PATCH {{host}}/cart/items/1
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "orderQuantity": 5
}

### CREATE ORDER
POST {{host}}/orders
Authorization: Bearer {{accessToken}}

### GET ORDERS
GET {{host}}/orders?page=0&size=10
Authorization: Bearer {{accessToken}}

### GET ORDER ITEMS
GET {{host}}/orders/1/items?page=0&size=10
Authorization: Bearer {{accessToken}}

### DELETE CART ITEM
DELETE {{host}}/cart/items/1
Authorization: Bearer {{accessToken}}

### DELETE PROFILE
DELETE {{host}}/users/me/profile
Authorization: Bearer {{accessToken}}

### DELETE USER
DELETE {{host}}/users/me
Authorization: Bearer {{accessToken}}
